<?php

declare(strict_types=1);

namespace PHPForge\Support\Tests;

use PHPForge\Support\EnumDataProvider;
use PHPForge\Support\Tests\Stub\TestEnum;
use PHPForge\Support\Tests\Support\Provider\EnumDataProviderProvider;
use PHPUnit\Framework\Attributes\{DataProviderExternal, Group};
use PHPUnit\Framework\TestCase;
use UnitEnum;

/**
 * Unit tests for {@see EnumDataProvider} enum dataset generation.
 *
 * Verifies datasets generated by {@see EnumDataProvider::attributeCases()} and {@see EnumDataProvider::tagCases()}.
 *
 * Test coverage.
 * - Generates attribute fragment datasets for enum cases.
 * - Generates tag datasets for enum cases.
 * - Normalizes `BackedEnum` and `UnitEnum` values for dataset keys and expected values.
 *
 * {@see EnumDataProvider} for implementation details.
 * {@see EnumDataProviderProvider} for test case data providers.
 *
 * @copyright Copyright (C) 2026 Terabytesoftw.
 * @license https://opensource.org/license/bsd-3-clause BSD 3-Clause License.
 */
#[Group('support')]
final class EnumDataProviderTest extends TestCase
{
    /**
     * @phpstan-param class-string<UnitEnum> $enumClass
     */
    #[DataProviderExternal(EnumDataProviderProvider::class, 'casesParameters')]
    public function testCasesGenerateExpectedStructure(
        string $enumClass,
        string|UnitEnum $attribute,
        bool $asHtml,
        string $expectedKeyCase,
        string $expectedAttributeCase,
        string $expectedMessage,
    ): void {
        $data = match ($asHtml) {
            true => EnumDataProvider::attributeCases($enumClass, $attribute),
            false => EnumDataProvider::attributeCases($enumClass, $attribute, false),
        };

        self::assertNotEmpty(
            $data,
            'Should return at least one data set.',
        );
        self::assertArrayHasKey(
            $expectedKeyCase,
            $data,
            'Should contain expected enum case in dataset.',
        );
        self::assertInstanceOf(
            $enumClass,
            $data[$expectedKeyCase][0] ?? null,
            'Should return expected enum case instance.',
        );

        if ($asHtml) {
            self::assertSame(
                $expectedAttributeCase,
                $data[$expectedKeyCase][2],
                'Should return expected attribute value for enum case.',
            );
        }

        self::assertSame(
            $expectedMessage,
            $data[$expectedKeyCase][3],
            'Should return expected message for enum case.',
        );
    }

    public function testTagCasesGenerateExpectedStructure(): void
    {
        $data = EnumDataProvider::tagCases(TestEnum::class, 'element');

        self::assertNotEmpty(
            $data,
            'Should return at least one data set.',
        );
        self::assertSame(
            [
                'BAR element tag' => [
                    TestEnum::BAR,
                    'BAR',
                ],
                'FOO element tag' => [
                    TestEnum::FOO,
                    'FOO',
                ],
            ],
            $data,
            'Should return expected tag cases dataset.',
        );
    }
}
